-- Open this file in ACS's 'Run SQL Scripts'
-- Replace 'OXBLIB' with your test library
-- To run all statements at once, press Ctrl+Shift+A 

CL: CRTLIB CRTLIB LIB(OJASVA) TYPE(*PROD) TEXT('Work Lib for Ojasva') ;
CL: CRTSRCPF FILE(OJASVA/QRPGLESRC) RCDLEN(112) TEXT('RPGLE Source Members') ;
CL: MKDIR DIR('/home/OJASVA') ;
-- *SECADM required to create or change user profiles.
CL: CHGUSRPRF USRPRF(OJASVA) HOMEDIR('/home/OJASVA') ;

SET SCHEMA OJASVA ;

CREATE TABLE QAUOOPT LIKE QGPL.QAUOOPT ;

-- Can also use the following statement
-- CREATE TABLE OXBLIB/QAUOOPT AS (SELECT * FROM QGPL/QAUOOPT) WITH NO DATA ;
-- If you want data in the new file, use the following statement
-- CREATE TABLE OXBLIB/QAUOOPT AS (SELECT * FROM QGPL/QAUOOPT) WITH DATA ;

INSERT INTO QAUOOPT VALUES(' C', 'CALL &O/&N') ;
INSERT INTO QAUOOPT VALUES(' Q', 'WRKMBRPDM FILE(OXBLIB/QTOOLSRC)') ;
INSERT INTO QAUOOPT VALUES(' W', 'WRKMBRPDM') ;
INSERT INTO QAUOOPT VALUES('AL', 'ADDLIBLE LIB(&L) POSITION(*FIRST)') ;
INSERT INTO QAUOOPT VALUES('BY', 'SIGNOFF LOG(*NOLIST) ENDCNN(*NO)') ;
INSERT INTO QAUOOPT VALUES('C1', 'CRTBNDCL PGM(&L/&N) SRCFILE(&L/&F) SRCMBR(&N) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('CC', 'CHGCURLIB CURLIB(&L)') ;
INSERT INTO QAUOOPT VALUES('CF', 'RUNSQLSTM SRCFILE(&L/&F) SRCMBR(&N) COMMIT(*NONE) DFTRDBCOL(&L)') ;
INSERT INTO QAUOOPT VALUES('CH', 'CHGPF FILE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('CL', 'CLRPFM FILE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('CM', 'CMPPFM NEWFILE(&L/&F) NEWMBR(&N) OLDFILE(&L/&F) OLDMBR(&N) CMPTYPE(*LINE)') ;
INSERT INTO QAUOOPT VALUES('CQ', 'CRTSQLRPGI OBJ(&L/&N) SRCFILE(&L/&F) SRCMBR(&N) COMMIT(*NONE) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('CS', 'CRTSRCPF FILE(&L/&F) RCDLEN(112)') ;
INSERT INTO QAUOOPT VALUES('CY', 'CPYSRCF FROMFILE(#IAEMG/&F) TOFILE(&L/&F) FROMMBR(&N) TOMBR(&N) MBROPT(*ADD)') ;
INSERT INTO QAUOOPT VALUES('DB', 'DSPDBR FILE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('DF', 'DSPFFD FILE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('DJ', 'DSPJOBLOG') ;
INSERT INTO QAUOOPT VALUES('DL', 'DSPLIBL') ;
INSERT INTO QAUOOPT VALUES('DM', 'DSPMODSRC') ;
INSERT INTO QAUOOPT VALUES('ED', 'ENDDBG') ;
INSERT INTO QAUOOPT VALUES('EL', 'EDTLIBL') ;
INSERT INTO QAUOOPT VALUES('IP', 'WRKTCPSTS *IFC') ;
INSERT INTO QAUOOPT VALUES('JL', 'DSPJOBLOG') ;
INSERT INTO QAUOOPT VALUES('LN', 'WRKLNK /') ;
INSERT INTO QAUOOPT VALUES('MR', 'MRGSRC TGTFILE(&L/&F) TGTMBR(&N) MAINTFILE(&L/&F) MAINTMBR(&N) ROOTFILE(&L/&F) ROOTMBR(&N)') ;
INSERT INTO QAUOOPT VALUES('P0', 'CRTPGM PGM(&L/&N) MODULE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('P1', 'RUNSQLSTM SRCFILE(&L/&F) SRCMBR(&N) COMMIT(*NONE) NAMING(*SYS) DFTRDBCOL(&L) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('QT', 'DSPLIB LIB(QTEMP)') ;
INSERT INTO QAUOOPT VALUES('R1', 'CRTBNDRPG PGM(&L/&N) SRCFILE(&L/&F) SRCMBR(&N) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('RQ', 'RUNQRY QRYFILE((&L/&N *FIRST))') ;
INSERT INTO QAUOOPT VALUES('S1', 'CRTSQLRPGI OBJ(&L/&N) SRCFILE(&L/&F) SRCMBR(&N) COMMIT(*NONE) OBJTYPE(*MODULE) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('SD', 'STRDBG PGM(&L/&N) UPDPROD(*YES) OPMSRC(*YES) DSPMODSRC(*YES)') ;
INSERT INTO QAUOOPT VALUES('SL', 'CALL PGM(OXBLIB/SETLIBLOXB)') ;
INSERT INTO QAUOOPT VALUES('SL', 'SBMJOB ??CMD(SAVLIB LIB(&N))') ;
INSERT INTO QAUOOPT VALUES('SM', 'SBMJOB ??CMD(SAVOBJ OBJ(&F) LIB(&L) OBJTYPE(*FILE) FILEMBR((&F (&N))))') ;
INSERT INTO QAUOOPT VALUES('SO', 'SBMJOB ??CMD(SAVOBJ OBJ(&N) LIB(&L))') ;
INSERT INTO QAUOOPT VALUES('SP', 'WRKSPLF') ;
INSERT INTO QAUOOPT VALUES('SQ', 'STRSQL') ;
INSERT INTO QAUOOPT VALUES('SV', 'STRDBG UPDPROD(*YES) OPMSRC(*YES) SRVPGM(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('UP', 'UPDDTA FILE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('US', 'UPDSRVPGM SRVPGM(&L/&N) MODULE(&L/&N)') ;
INSERT INTO QAUOOPT VALUES('WA', 'WRKACTJOB SBS(QINTER)') ;
INSERT INTO QAUOOPT VALUES('WO', 'WRKOBJ &L/&N') ;
INSERT INTO QAUOOPT VALUES('WS', 'WRKSBMJOB') ;
INSERT INTO QAUOOPT VALUES('WU', 'WRKUSRJOB') ;
INSERT INTO QAUOOPT VALUES('Y9', 'SIGNOFF ENDCNN(*YES)') ;
INSERT INTO QAUOOPT VALUES('YC', 'CMPPFM NEWFILE(&L/&F) NEWMBR(&N) OLDFILE(#IAEMG/&F) OLDMBR(&N)') ;
INSERT INTO QAUOOPT VALUES('YC', 'CRTBNDCL PGM(&L/&N) SRCFILE(&L/&F) REPLACE(*YES) DBGVIEW(*LIST)') ;
INSERT INTO QAUOOPT VALUES('YD', 'DLTSPLF FILE(*SELECT)') ;
INSERT INTO QAUOOPT VALUES('YD', 'DLTSPLF FILE(*SELECT)') ;
INSERT INTO QAUOOPT VALUES('YM', 'MRGSRC TGTFILE(&L/&F) TGTMBR(&N) MAINTFILE(&L/&F) MAINTMBR(TEST) ROOTFILE(&L/&F) ROOTMBR(&N)') ;
INSERT INTO QAUOOPT VALUES('YR', 'CRTBNDRPG PGM(&L/&N) SRCFILE(&F) DBGVIEW(*SOURCE)') ;
INSERT INTO QAUOOPT VALUES('YS', 'CRTSQLRPGI OBJ(&L/&N) SRCFILE(&L/&F) DBGVIEW(*LIST)') ;

CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'AI') ;
CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'IA') ;
CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'S1') ;
CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'S2') ;
CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'S3') ;
CL: CPYF FROMFILE(QGPL/QAUOOPT) TOFILE(OJASVA/QAUOOPT) MBROPT(*ADD) INCCHAR(*FLD 1 *EQ 'SV') ;
